# Generated by Django 5.2 on 2025-11-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('cod_dum', models.CharField(max_length=50)),
                ('cod_ean', models.CharField(max_length=50)),
                ('cod_sistema', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('area_solicitud', models.CharField(max_length=100)),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('cantidad_solicitada', models.IntegerField()),
                ('status_prioridades', models.CharField(max_length=50)),
                ('cant_enviada_bsf', models.IntegerField(default=0)),
                ('chofer', models.CharField(blank=True, max_length=100, null=True)),
                ('factura_guia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
